name: Auto Commit Daily

on:
  schedule:
    - cron: '0 1,5,9,13,17,21 * * *'
   
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Random delay
        run: |
          DELAY=$((RANDOM % 600))  # random 0-10 menit
          echo "Delay $DELAY detik"
          sleep $DELAY

      - name: Update log file
        run: |
          mkdir -p .autocommit
          echo "Update on $(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> .autocommit/activity.log

      - name: Commit and push
        run: |
          git config user.name "mikhaelle-dev"
          git config user.email "mikhaelrakarenzo@gmail.com"
          git add .autocommit/activity.log
          git diff --staged --quiet || git commit -m "chore: daily auto update"
          git push